# https://yarnpkg.com/configuration/yarnrc

approvedGitRepositories:
  - '**'
changesetBaseRefs: 1.0.0-beta.2
changesetIgnorePatterns:
  - '**/__snapshots__/**'
  - '**/__tests__/**'
  - '*.*'
  - '__fixtures__/**'
  - .github/**
  - .husky/**
  - .vscode/**
  - .yarn/releases/**
  - dprint/**
  - scripts/**
  - typings/**
compressionLevel: mixed
defaultSemverRangePrefix: ''
enableGlobalCache: false
enableInlineBuilds: true
enableScripts: true
enableTransparentWorkspaces: false
injectEnvironmentFiles:
  - .env.repo?
  - .env.vars?
nmHoistingLimits: dependencies
nodeLinker: node-modules
npmMinimalAgeGate: 0
patchFolder: ./patches
preferDeferredVersions: true
yarnPath: .yarn/releases/yarn-4.18.1.cjs
